---
catalog:
  zod: ^3.23.8
catalogs:
  jotai:
    bunshi: ^2.1.5
    jotai: ^2.12.5
    jotai-effect: ^1.0.0
    jotai-immer: ^0.4.1
    jotai-optics: ^0.4.0
    jotai-scope: ^0.7.0
    jotai-tanstack-query: ^0.8.5
    jotai-xstate: ^0.6.1
    jotai-history: ^0.2.1
    jotai-location: ^0.5.5
  pixi:
    "@pixi/layout": ^3.1.0
    "@pixi/react": ^8.0.3
    "@pixi/sound": ^6.0.1
    "@pixi/text": ^7.4.3
    "@pixi/tilemap": ^5.0.1
    pixi-viewport: ^6.0.3
    pixi.js: ^8.12.1
  react:
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
    react: 19.1.0
    react-dom: 19.1.0
packages:
  - packages/*
