---
catalog:
  zod: ^3.23.8
catalogs:
  react:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': 19.1.8
    '@types/react-dom': 19.1.6
  pixi:
    '@pixi/layout': ^3.0.2
    '@pixi/react': 8.0.2
    '@pixi/text': ^7.4.3
    '@pixi/tilemap': ^5.0.1
    '@pixi/ui': ^2.2.4
    pixi-viewport: ^6.0.3
    pixi.js: ^8.10.1
packages:

  - packages/*